import * as pdfjsLib from "pdfjs-dist";
import { getPdfBuffer } from "../api";

pdfjsLib.GlobalWorkerOptions.workerSrc = new URL(
  "pdfjs-dist/build/pdf.worker.mjs",
  import.meta.url
).toString();

function stripTags(html) {
  return html.replace(/<[^>]*>/g, "");
}

function formatDate() {
  return new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
    hour: "2-digit", minute: "2-digit",
  });
}

export async function printMatchedPages(results, onProgress) {
  // Deduplicate by file + page
  const seen   = new Set();
  const unique = results.filter(r => {
    const k = `${r.file_name}::${r.page_number}`;
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });

  const totalPages = unique.length;
  const fileNames  = [...new Set(unique.map(r => r.file_name))];
  const query      = stripTags(results[0]?.snippet || "").trim();

  onProgress(`Preparing ${totalPages} page(s) for print…`);

  // Load & render each page
  const pdfCache = {};
  const rendered = [];

  for (let i = 0; i < unique.length; i++) {
    const { file_name, page_number, snippet } = unique[i];
    onProgress(`Rendering ${i + 1} / ${totalPages} — ${file_name} p.${page_number}`);

    if (!pdfCache[file_name]) {
      const buf = await getPdfBuffer(file_name);
      pdfCache[file_name] = await pdfjsLib.getDocument({ data: new Uint8Array(buf) }).promise;
    }

    const pdf      = pdfCache[file_name];
    const page     = await pdf.getPage(page_number);
    const viewport = page.getViewport({ scale: 2.2 });

    const canvas = document.createElement("canvas");
    canvas.width  = viewport.width;
    canvas.height = viewport.height;
    await page.render({ canvasContext: canvas.getContext("2d"), viewport }).promise;

    rendered.push({
      dataUrl: canvas.toDataURL("image/jpeg", 0.93),
      file_name,
      page_number,
      snippet,
    });
  }

  onProgress("Opening print dialog…");

  const printedAt = formatDate();

  const coverHtml = `
<div class="cover">
  <div class="cover-brand">
    <div class="cover-logo">
      <svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" width="28" height="28">
        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
        <polyline points="14,2 14,8 20,8"/>
        <circle cx="11" cy="15" r="3"/>
        <line x1="13.5" y1="17.5" x2="16" y2="20"/>
      </svg>
    </div>
    <div>
      <div class="cover-app-name">PDF Search</div>
      <div class="cover-app-sub">Search Results Report</div>
    </div>
  </div>

  <div class="cover-divider"></div>

  <div class="cover-meta-grid">
    <div class="cover-meta-item">
      <div class="cover-meta-label">PRINTED ON</div>
      <div class="cover-meta-value">${printedAt}</div>
    </div>
    <div class="cover-meta-item">
      <div class="cover-meta-label">MATCHED PAGES</div>
      <div class="cover-meta-value">${totalPages} page${totalPages !== 1 ? "s" : ""}</div>
    </div>
    <div class="cover-meta-item">
      <div class="cover-meta-label">SOURCE FILES</div>
      <div class="cover-meta-value">${fileNames.length} file${fileNames.length !== 1 ? "s" : ""}</div>
    </div>
  </div>

  <div class="cover-files">
    <div class="cover-meta-label" style="margin-bottom:8px;">INDEXED FILES IN THIS REPORT</div>
    ${fileNames.map((f, i) => `
      <div class="cover-file-row">
        <span class="cover-file-num">${String(i + 1).padStart(2, "0")}</span>
        <span class="cover-file-name">${f}</span>
        <span class="cover-file-pages">${unique.filter(r => r.file_name === f).length} page(s) matched</span>
      </div>
    `).join("")}
  </div>

  <div class="cover-footer">
    Generated by PDF Search · 100% Offline · No Cloud
  </div>
</div>`;

  const pagesHtml = rendered.map((r, i) => `
<div class="result-page">

  <div class="page-header">
    <div class="page-header-left">
      <div class="page-header-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.2" width="14" height="14">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
          <polyline points="14,2 14,8 20,8"/>
        </svg>
      </div>
      <div>
        <div class="page-file-name">${r.file_name}</div>
      </div>
    </div>
    <div class="page-header-right">
      <span class="page-badge">Page ${r.page_number}</span>
      <span class="page-counter">${i + 1} / ${totalPages}</span>
    </div>
  </div>

  <div class="match-bar">
    <span class="match-label">MATCHED TEXT</span>
    <span class="match-text">${r.snippet.replace(/<mark>/g, '<span class="hl">').replace(/<\/mark>/g, '</span>')}</span>
  </div>

  <div class="page-image-wrap">
    <img class="page-image" src="${r.dataUrl}" alt="Page ${r.page_number}" />
  </div>

  <div class="page-footer">
    <span class="footer-app">PDF Search Report</span>
    <span class="footer-sep">·</span>
    <span class="footer-file">${r.file_name}</span>
    <span class="footer-sep">·</span>
    <span class="footer-date">${printedAt}</span>
    <span class="footer-pagenum">${i + 1} / ${totalPages}</span>
  </div>

</div>`).join("\n");

  const css = `
    @page { margin: 0; size: A4 portrait; }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
      background: #fff;
      color: #0f172a;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    /* ── Cover page ────────────────────────────────── */
    .cover {
      width: 100%;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      padding: 56px 52px;
      page-break-after: always;
      background: #fff;
      position: relative;
    }

    .cover::before {
      content: "";
      position: absolute;
      top: 0; left: 0; right: 0;
      height: 6px;
      background: linear-gradient(90deg, #6366f1, #8b5cf6, #06b6d4);
    }

    .cover-brand {
      display: flex;
      align-items: center;
      gap: 16px;
      margin-bottom: 48px;
    }

    .cover-logo {
      width: 52px; height: 52px;
      background: linear-gradient(135deg, #6366f1, #8b5cf6);
      border-radius: 14px;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    .cover-app-name {
      font-size: 28px;
      font-weight: 800;
      color: #0f172a;
      letter-spacing: -0.5px;
    }

    .cover-app-sub {
      font-size: 13px;
      color: #64748b;
      font-weight: 500;
      margin-top: 2px;
    }

    .cover-divider {
      height: 1px;
      background: linear-gradient(90deg, #6366f1 0%, #e2e8f0 60%);
      margin-bottom: 36px;
    }

    .cover-meta-grid {
      display: flex;
      gap: 0;
      margin-bottom: 40px;
    }

    .cover-meta-item {
      flex: 1;
      padding: 20px 24px;
      border: 1px solid #e2e8f0;
      border-right: none;
    }
    .cover-meta-item:first-child { border-radius: 10px 0 0 10px; }
    .cover-meta-item:last-child  { border-right: 1px solid #e2e8f0; border-radius: 0 10px 10px 0; }

    .cover-meta-label {
      font-size: 9px;
      font-weight: 800;
      letter-spacing: 1.2px;
      color: #94a3b8;
      text-transform: uppercase;
      margin-bottom: 6px;
    }

    .cover-meta-value {
      font-size: 18px;
      font-weight: 700;
      color: #0f172a;
    }

    .cover-files {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 10px;
      padding: 20px 24px;
      margin-bottom: auto;
    }

    .cover-file-row {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 10px 0;
      border-bottom: 1px solid #f1f5f9;
    }
    .cover-file-row:last-child { border-bottom: none; }

    .cover-file-num {
      font-size: 11px;
      font-weight: 700;
      color: #6366f1;
      width: 24px;
      flex-shrink: 0;
    }

    .cover-file-name {
      font-size: 13px;
      font-weight: 600;
      color: #1e293b;
      flex: 1;
    }

    .cover-file-pages {
      font-size: 11px;
      color: #64748b;
      background: #eef2ff;
      padding: 2px 10px;
      border-radius: 20px;
      white-space: nowrap;
    }

    .cover-footer {
      margin-top: 48px;
      font-size: 11px;
      color: #94a3b8;
      text-align: center;
      letter-spacing: 0.3px;
    }

    /* ── Result pages ──────────────────────────────── */
    .result-page {
      width: 100%;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      page-break-after: always;
      background: #fff;
    }
    .result-page:last-child { page-break-after: auto; }

    .page-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 12px 20px;
      background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
      gap: 12px;
      flex-shrink: 0;
    }

    .page-header-left {
      display: flex;
      align-items: center;
      gap: 10px;
      min-width: 0;
    }

    .page-header-icon {
      width: 30px; height: 30px;
      background: rgba(99,102,241,0.3);
      border-radius: 7px;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    .page-file-name {
      font-size: 12px;
      font-weight: 700;
      color: #f1f5f9;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
      max-width: 420px;
    }

    .page-header-right {
      display: flex;
      align-items: center;
      gap: 10px;
      flex-shrink: 0;
    }

    .page-badge {
      font-size: 11px;
      font-weight: 700;
      color: #a5b4fc;
      background: rgba(99,102,241,0.2);
      padding: 3px 10px;
      border-radius: 20px;
      border: 1px solid rgba(99,102,241,0.3);
    }

    .page-counter {
      font-size: 11px;
      color: #64748b;
      font-weight: 500;
    }

    .match-bar {
      display: flex;
      align-items: baseline;
      gap: 10px;
      padding: 9px 20px;
      background: #fffbeb;
      border-bottom: 2px solid #fde68a;
      flex-shrink: 0;
    }

    .match-label {
      font-size: 8.5px;
      font-weight: 800;
      letter-spacing: 1px;
      color: #92400e;
      white-space: nowrap;
      text-transform: uppercase;
    }

    .match-text {
      font-size: 11.5px;
      color: #78350f;
      line-height: 1.5;
    }

    .hl {
      background: #fef08a;
      color: #713f12;
      font-weight: 700;
      border-radius: 2px;
      padding: 0 2px;
    }

    .page-image-wrap {
      flex: 1;
      display: flex;
      align-items: flex-start;
      justify-content: center;
      background: #f0f4f8;
      padding: 20px;
    }

    .page-image {
      width: 100%;
      max-width: 720px;
      height: auto;
      display: block;
      box-shadow: 0 4px 24px rgba(0,0,0,0.12);
      border-radius: 4px;
      background: #fff;
    }

    .page-footer {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 8px 20px;
      background: #f8fafc;
      border-top: 1px solid #e2e8f0;
      font-size: 10px;
      color: #94a3b8;
      flex-shrink: 0;
    }

    .footer-sep { color: #cbd5e1; }

    .footer-file {
      color: #64748b;
      flex: 1;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .footer-pagenum {
      font-weight: 700;
      color: #6366f1;
      margin-left: auto;
    }
  `;

  const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>PDF Search — Results Report</title>
<style>${css}</style>
</head>
<body>
${coverHtml}
${pagesHtml}
</body>
</html>`;

  // Print via hidden iframe
  const iframe = document.createElement("iframe");
  iframe.style.cssText = "position:fixed;top:-9999px;left:-9999px;width:1px;height:1px;border:none;";
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow.document;
  doc.open();
  doc.write(fullHtml);
  doc.close();

  // Wait for images to fully load before triggering print
  await new Promise(resolve => {
    const imgs = doc.querySelectorAll("img");
    if (!imgs.length) { resolve(); return; }
    let loaded = 0;
    imgs.forEach(img => {
      if (img.complete) { if (++loaded === imgs.length) resolve(); }
      else { img.onload = img.onerror = () => { if (++loaded === imgs.length) resolve(); }; }
    });
    // Fallback timeout
    setTimeout(resolve, 3000);
  });

  iframe.contentWindow.focus();
  iframe.contentWindow.print();

  setTimeout(() => {
    if (document.body.contains(iframe)) document.body.removeChild(iframe);
  }, 8000);
}
